--Ingresa fecha de registro al crear una Actividad.
CREATE OR REPLACE trigger "BI_TB_ACTIVIDADES_DATE"  
  before insert on "TB_ACTIVIDAD"              
  for each row 
begin  
    :NEW.FECHAREGISTRO := sysdate;
end;
********************************************************************************************************************
********************************************************************************************************************

--Ingresa fecha de registro de horas de desarrollo.
CREATE OR REPLACE trigger "BI_TB_HORAS_DES_DATE"  
  before insert on "TB_HORAS_DESARROLLO"              
  for each row 
begin  
    :NEW.FECHAREGISTRO := sysdate;
end;
********************************************************************************************************************
********************************************************************************************************************

--Triggers de auditoria

--TRIGGER CON AFTER PARA TODOS LOS DML


CREATE OR REPLACE TRIGGER AFT_AUDI_TB_ACTIVIDAD
	AFTER DELETE OR UPDATE OR INSERT ON TB_ACTIVIDAD
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDACTIVIDAD',
				'INSERT',
				:OLD.IDACTIVIDAD,
				:NEW.IDACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
	
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'DESCRIPCION',
				'INSERT',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'TITULO',
				'INSERT',
				:OLD.TITULO,
				:NEW.TITULO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'VERSION',
				'INSERT',
				:OLD.VERSION,
				:NEW.VERSION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'CODIGOSISTEMACLIENTE',
				'INSERT',
				:OLD.CODIGOSISTEMACLIENTE,
				:NEW.CODIGOSISTEMACLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'FECHAREGISTRO',
				'INSERT',
				:OLD.FECHAREGISTRO,
				:NEW.FECHAREGISTRO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDTIPOACTIVIDAD',
				'INSERT',
				:OLD.IDTIPOACTIVIDAD,
				:NEW.IDTIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDCLIENTE',
				'INSERT',
				:OLD.IDCLIENTE,
				:NEW.IDCLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDAPLICACION',
				'INSERT',
				:OLD.IDAPLICACION,
				:NEW.IDAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDACTIVIDAD);
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDACTIVIDAD',
				'UPDATE',
				:OLD.IDACTIVIDAD,
				:NEW.IDACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
	
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'DESCRIPCION',
				'UPDATE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'TITULO',
				'UPDATE',
				:OLD.TITULO,
				:NEW.TITULO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'VERSION',
				'UPDATE',
				:OLD.VERSION,
				:NEW.VERSION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'CODIGOSISTEMACLIENTE',
				'UPDATE',
				:OLD.CODIGOSISTEMACLIENTE,
				:NEW.CODIGOSISTEMACLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'FECHAREGISTRO',
				'UPDATE',
				:OLD.FECHAREGISTRO,
				:NEW.FECHAREGISTRO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDTIPOACTIVIDAD',
				'UPDATE',
				:OLD.IDTIPOACTIVIDAD,
				:NEW.IDTIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDCLIENTE',
				'UPDATE',
				:OLD.IDCLIENTE,
				:NEW.IDCLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDAPLICACION',
				'UPDATE',
				:OLD.IDAPLICACION,
				:NEW.IDAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDACTIVIDAD',
				'DELETE',
				:OLD.IDACTIVIDAD,
				:NEW.IDACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
	
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'DESCRIPCION',
				'DELETE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'TITULO',
				'DELETE',
				:OLD.TITULO,
				:NEW.TITULO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'VERSION',
				'DELETE',
				:OLD.VERSION,
				:NEW.VERSION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'CODIGOSISTEMACLIENTE',
				'DELETE',
				:OLD.CODIGOSISTEMACLIENTE,
				:NEW.CODIGOSISTEMACLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'FECHAREGISTRO',
				'DELETE',
				:OLD.FECHAREGISTRO,
				:NEW.FECHAREGISTRO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDTIPOACTIVIDAD',
				'DELETE',
				:OLD.IDTIPOACTIVIDAD,
				:NEW.IDTIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDCLIENTE',
				'DELETE',
				:OLD.IDCLIENTE,
				:NEW.IDCLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ACTIVIDAD',
				'IDAPLICACION',
				'DELETE',
				:OLD.IDAPLICACION,
				:NEW.IDAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDACTIVIDAD);
	END IF;	
END;


********************************************************************************************************************
********************************************************************************************************************
CREATE OR REPLACE TRIGGER AFT_AUDI_TB_APP_AFECTADA
	AFTER DELETE OR UPDATE OR INSERT ON TB_APLICACION_AFECTADA
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_APLICACION_AFECTADA',
				'IDAPLICACION',
				'INSERT',
				:OLD.IDAPLICACION,
				:NEW.IDAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDAPLICACION);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_APLICACION_AFECTADA',
				'NOMBREAPLICACION',
				'INSERT',
				:OLD.NOMBREAPLICACION,
				:NEW.NOMBREAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDAPLICACION);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_APLICACION_AFECTADA',
				'IDAPLICACION',
				'UPDATE',
				:OLD.IDAPLICACION,
				:NEW.IDAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDAPLICACION);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_APLICACION_AFECTADA',
				'NOMBREAPLICACION',
				'UPDATE',
				:OLD.NOMBREAPLICACION,
				:NEW.NOMBREAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDAPLICACION);
	
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_APLICACION_AFECTADA',
				'IDAPLICACION',
				'DELETE',
				:OLD.IDAPLICACION,
				:NEW.IDAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDAPLICACION);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_APLICACION_AFECTADA',
				'NOMBREAPLICACION',
				'DELETE',
				:OLD.NOMBREAPLICACION,
				:NEW.NOMBREAPLICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDAPLICACION);
        
	END IF;	
END;


********************************************************************************************************************
********************************************************************************************************************
CREATE OR REPLACE TRIGGER AFT_AUDI_TB_CLIENTE
	AFTER DELETE OR UPDATE OR INSERT ON TB_CLIENTE
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_CLIENTE',
				'IDCLIENTE',
				'INSERT',
				:OLD.IDCLIENTE,
				:NEW.IDCLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDCLIENTE);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_CLIENTE',
				'NOMBRE',
				'INSERT',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDCLIENTE);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_CLIENTE',
				'IDCLIENTE',
				'UPDATE',
				:OLD.IDCLIENTE,
				:NEW.IDCLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDCLIENTE);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_CLIENTE',
				'NOMBRE',
				'UPDATE',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDCLIENTE);
	
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_CLIENTE',
				'IDCLIENTE',
				'DELETE',
				:OLD.IDCLIENTE,
				:NEW.IDCLIENTE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDCLIENTE);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_CLIENTE',
				'NOMBRE',
				'DELETE',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDCLIENTE);
	
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************

CREATE OR REPLACE TRIGGER AFT_AUDI_TB_ESTADO
	AFTER DELETE OR UPDATE OR INSERT ON TB_ESTADO
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ESTADO',
				'IDESTADO',
				'INSERT',
				:OLD.IDESTADO,
				:NEW.IDESTADO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDESTADO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ESTADO',
				'DESCRIPCION',
				'INSERT',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDESTADO);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ESTADO',
				'IDESTADO',
				'UPDATE',
				:OLD.IDESTADO,
				:NEW.IDESTADO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDESTADO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ESTADO',
				'DESCRIPCION',
				'UPDATE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDESTADO);
	
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ESTADO',
				'IDESTADO',
				'DELETE',
				:OLD.IDESTADO,
				:NEW.IDESTADO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDESTADO);
	
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_ESTADO',
				'DESCRIPCION',
				'DELETE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDESTADO);
        
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************	

CREATE OR REPLACE TRIGGER AFT_AUDI_TB_FABRICA
	AFTER DELETE OR UPDATE OR INSERT ON TB_FABRICA
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_FABRICA',
				'IDFABRICA',
				'INSERT',
				:OLD.IDFABRICA,
				:NEW.IDFABRICA,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDFABRICA);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_FABRICA',
				'DESCRIPCION',
				'INSERT',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDFABRICA);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_FABRICA',
				'IDFABRICA',
				'UPDATE',
				:OLD.IDFABRICA,
				:NEW.IDFABRICA,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDFABRICA);
	
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_FABRICA',
				'DESCRIPCION',
				'UPDATE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDFABRICA);
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_FABRICA',
				'IDFABRICA',
				'DELETE',
				:OLD.IDFABRICA,
				:NEW.IDFABRICA,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDFABRICA);
		
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_FABRICA',
				'DESCRIPCION',
				'DELETE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDFABRICA);
        
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************


CREATE OR REPLACE TRIGGER AFT_AUDI_TB_GRUPO
	AFTER DELETE OR UPDATE OR INSERT ON TB_GRUPO
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'IDGRUPO',
				'INSERT',
				:OLD.IDGRUPO,
				:NEW.IDGRUPO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDGRUPO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'NOMBRE',
				'INSERT',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDGRUPO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'IDFABRICA',
				'INSERT',
				:OLD.IDFABRICA,
				:NEW.IDFABRICA,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDGRUPO);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'IDGRUPO',
				'UPDATE',
				:OLD.IDGRUPO,
				:NEW.IDGRUPO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDGRUPO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'NOMBRE',
				'UPDATE',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDGRUPO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'IDFABRICA',
				'UPDATE',
				:OLD.IDFABRICA,
				:NEW.IDFABRICA,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDGRUPO);
	
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'IDGRUPO',
				'DELETE',
				:OLD.IDGRUPO,
				:NEW.IDGRUPO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDGRUPO);
		
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'NOMBRE',
				'DELETE',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDGRUPO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_GRUPO',
				'IDFABRICA',
				'DELETE',
				:OLD.IDFABRICA,
				:NEW.IDFABRICA,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDGRUPO);
        
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************

CREATE OR REPLACE TRIGGER AFT_AUDI_TB_HORAS_DESARROLLO
	AFTER DELETE OR UPDATE OR INSERT ON TB_HORAS_DESARROLLO
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDHORAS',
				'INSERT',
				:OLD.IDHORAS,
				:NEW.IDHORAS,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'DESCRIPCION',
				'INSERT',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAREGISTRO',
				'INSERT',
				:OLD.FECHAREGISTRO,
				:NEW.FECHAREGISTRO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAINICIO',
				'INSERT',
				:OLD.FECHAINICIO,
				:NEW.FECHAINICIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAFIN',
				'INSERT',
				:OLD.FECHAFIN,
				:NEW.FECHAFIN,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDUSUARIO',
				'INSERT',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDACTIVIDAD',
				'INSERT',
				:OLD.IDACTIVIDAD,
				:NEW.IDACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDHORAS);
				
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDHORAS',
				'UPDATE',
				:OLD.IDHORAS,
				:NEW.IDHORAS,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'DESCRIPCION',
				'UPDATE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAREGISTRO',
				'UPDATE',
				:OLD.FECHAREGISTRO,
				:NEW.FECHAREGISTRO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAINICIO',
				'UPDATE',
				:OLD.FECHAINICIO,
				:NEW.FECHAINICIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAFIN',
				'UPDATE',
				:OLD.FECHAFIN,
				:NEW.FECHAFIN,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDUSUARIO',
				'UPDATE',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDACTIVIDAD',
				'UPDATE',
				:OLD.IDACTIVIDAD,
				:NEW.IDACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDHORAS',
				'DELETE',
				:OLD.IDHORAS,
				:NEW.IDHORAS,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'DESCRIPCION',
				'DELETE',
				:OLD.DESCRIPCION,
				:NEW.DESCRIPCION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAREGISTRO',
				'DELETE',
				:OLD.FECHAREGISTRO,
				:NEW.FECHAREGISTRO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAINICIO',
				'DELETE',
				:OLD.FECHAINICIO,
				:NEW.FECHAINICIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'FECHAFIN',
				'DELETE',
				:OLD.FECHAFIN,
				:NEW.FECHAFIN,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDUSUARIO',
				'DELETE',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_HORAS_DESARROLLO',
				'IDACTIVIDAD',
				'DELETE',
				:OLD.IDACTIVIDAD,
				:NEW.IDACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDHORAS);
	
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************

CREATE OR REPLACE TRIGGER AFT_AUDI_TB_LOGIN
	AFTER DELETE OR UPDATE OR INSERT ON TB_LOGIN
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'IDLOGIN',
				'INSERT',
				:OLD.IDLOGIN,
				:NEW.IDLOGIN,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'USUARIORED',
				'INSERT',
				:OLD.USUARIORED,
				:NEW.USUARIORED,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'ESTADO',
				'INSERT',
				:OLD.ESTADO,
				:NEW.ESTADO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'IDUSUARIO',
				'INSERT',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'PASSWORD',
				'INSERT',
				:OLD.PASSWORD,
				:NEW.PASSWORD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDLOGIN);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'IDLOGIN',
				'UPDATE',
				:OLD.IDLOGIN,
				:NEW.IDLOGIN,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'USUARIORED',
				'UPDATE',
				:OLD.USUARIORED,
				:NEW.USUARIORED,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'ESTADO',
				'UPDATE',
				:OLD.ESTADO,
				:NEW.ESTADO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'IDUSUARIO',
				'UPDATE',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'PASSWORD',
				'UPDATE',
				:OLD.PASSWORD,
				:NEW.PASSWORD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
	
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'IDLOGIN',
				'DELETE',
				:OLD.IDLOGIN,
				:NEW.IDLOGIN,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'USUARIORED',
				'DELETE',
				:OLD.USUARIORED,
				:NEW.USUARIORED,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'ESTADO',
				'DELETE',
				:OLD.ESTADO,
				:NEW.ESTADO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
		
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'IDUSUARIO',
				'DELETE',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_LOGIN',
				'PASSWORD',
				'DELETE',
				:OLD.PASSWORD,
				:NEW.PASSWORD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDLOGIN);
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************

CREATE OR REPLACE TRIGGER AFT_AUDI_TB_PERFILES
	AFTER DELETE OR UPDATE OR INSERT ON TB_PERFILES
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_PERFILES',
				'IDPERFIL',
				'INSERT',
				:OLD.IDPERFIL,
				:NEW.IDPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDPERFIL);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_PERFILES',
				'NOMBREPERFIL',
				'INSERT',
				:OLD.NOMBREPERFIL,
				:NEW.NOMBREPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDPERFIL);
		
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_PERFILES',
				'IDPERFIL',
				'UPDATE',
				:OLD.IDPERFIL,
				:NEW.IDPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDPERFIL);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_PERFILES',
				'NOMBREPERFIL',
				'UPDATE',
				:OLD.NOMBREPERFIL,
				:NEW.NOMBREPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDPERFIL);
	
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_PERFILES',
				'IDPERFIL',
				'DELETE',
				:OLD.IDPERFIL,
				:NEW.IDPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDPERFIL);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_PERFILES',
				'NOMBREPERFIL',
				'UPDATE',
				:OLD.NOMBREPERFIL,
				:NEW.NOMBREPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDPERFIL);
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************

CREATE OR REPLACE TRIGGER AFT_AUDI_TB_TIPOACTIVIDAD
	AFTER DELETE OR UPDATE OR INSERT ON TB_TIPOACTIVIDAD
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_TIPOACTIVIDAD',
				'IDTIPOACTIVIDAD',
				'INSERT',
				:OLD.IDTIPOACTIVIDAD,
				:NEW.IDTIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDTIPOACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_TIPOACTIVIDAD',
				'NOMBRETIPOACTIVIDAD',
				'INSERT',
				:OLD.NOMBRETIPOACTIVIDAD,
				:NEW.NOMBRETIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDTIPOACTIVIDAD);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_TIPOACTIVIDAD',
				'IDTIPOACTIVIDAD',
				'UPDATE',
				:OLD.IDTIPOACTIVIDAD,
				:NEW.IDTIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDTIPOACTIVIDAD);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_TIPOACTIVIDAD',
				'NOMBRETIPOACTIVIDAD',
				'UPDATE',
				:OLD.NOMBRETIPOACTIVIDAD,
				:NEW.NOMBRETIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDTIPOACTIVIDAD);
	
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_TIPOACTIVIDAD',
				'IDTIPOACTIVIDAD',
				'DELETE',
				:OLD.IDTIPOACTIVIDAD,
				:NEW.IDTIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDTIPOACTIVIDAD);
		
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_TIPOACTIVIDAD',
				'NOMBRETIPOACTIVIDAD',
				'DELETE',
				:OLD.NOMBRETIPOACTIVIDAD,
				:NEW.NOMBRETIPOACTIVIDAD,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDTIPOACTIVIDAD);
        
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************

CREATE OR REPLACE TRIGGER AFT_AUDI_TB_USUARIOS
	AFTER DELETE OR UPDATE OR INSERT ON TB_USUARIOS
	FOR EACH ROW
	BEGIN 
	IF (INSERTING) THEN
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDUSUARIO',
				'INSERT',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'COSTO',
				'INSERT',
				:OLD.COSTO,
				:NEW.COSTO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'CORREO',
				'INSERT',
				:OLD.CORREO,
				:NEW.CORREO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'TELEFONO',
				'INSERT',
				:OLD.TELEFONO,
				:NEW.TELEFONO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDENTIFICACION',
				'INSERT',
				:OLD.IDENTIFICACION,
				:NEW.IDENTIFICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'NOMBRE',
				'INSERT',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDPERFIL',
				'INSERT',
				:OLD.IDPERFIL,
				:NEW.IDPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDGRUPO',
				'INSERT',
				:OLD.IDGRUPO,
				:NEW.IDGRUPO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:NEW.IDUSUARIO);
	
	END IF;
	
    IF (UPDATING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDUSUARIO',
				'UPDATE',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'COSTO',
				'UPDATE',
				:OLD.COSTO,
				:NEW.COSTO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'CORREO',
				'UPDATE',
				:OLD.CORREO,
				:NEW.CORREO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'TELEFONO',
				'UPDATE',
				:OLD.TELEFONO,
				:NEW.TELEFONO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDENTIFICACION',
				'UPDATE',
				:OLD.IDENTIFICACION,
				:NEW.IDENTIFICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'NOMBRE',
				'UPDATE',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDPERFIL',
				'UPDATE',
				:OLD.IDPERFIL,
				:NEW.IDPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDGRUPO',
				'UPDATE',
				:OLD.IDGRUPO,
				:NEW.IDGRUPO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
	END IF;
	
	IF (DELETING) THEN
        INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDUSUARIO',
				'DELETE',
				:OLD.IDUSUARIO,
				:NEW.IDUSUARIO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'COSTO',
				'DELETE',
				:OLD.COSTO,
				:NEW.COSTO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'CORREO',
				'DELETE',
				:OLD.CORREO,
				:NEW.CORREO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'TELEFONO',
				'DELETE',
				:OLD.TELEFONO,
				:NEW.TELEFONO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDENTIFICACION',
				'DELETE',
				:OLD.IDENTIFICACION,
				:NEW.IDENTIFICACION,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'NOMBRE',
				'DELETE',
				:OLD.NOMBRE,
				:NEW.NOMBRE,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDPERFIL',
				'DELETE',
				:OLD.IDPERFIL,
				:NEW.IDPERFIL,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
				
		INSERT INTO TB_AUDITORIA (TABLA,CAMPO,ACCION,DATOANTIGUO,DATONUEVO,DIRECCIONIP,FECHAOPERACION,IDREGISTROTABLA) 
		VALUES(	'TB_USUARIOS',
				'IDGRUPO',
				'DELETE',
				:OLD.IDGRUPO,
				:NEW.IDGRUPO,
				sys_context('USERENV','IP_ADDRESS'),
				sysdate,:OLD.IDUSUARIO);
	END IF;	
END;

********************************************************************************************************************
********************************************************************************************************************
